# note: this file is not in use
# since I decided to use `x86_64-unknown-none` instead of `x86_64-my_os.json`

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-my_os.json"
